name: facebook/react/devtools_regression_tests
on:
  schedule:
  - cron: 0 0 * * *
#   # 'filters' was not transformed because there is no suitable equivalent in GitHub Actions
  workflow_dispatch:
    inputs:
      prerelease_commit_sha:
        required: true
env:
  CIRCLE_CI_API_TOKEN: xxxx6989
  NPM_TOKEN: xxxxJBvP
jobs:
  download_build:
    if: ${{ !(${{ inputs.prerelease_commit_sha }}) }}
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:18.0-node
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      revision: "${{ github.event.pull_request.head.sha }}"
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/setup_node_modules"
    - name: Download artifacts for revision
      run: |-
        git fetch origin main
        cd ./scripts/release && yarn && cd ../../
        scripts/release/download-experimental-build.js --commit=${{ env.revision }} --allowBrokenCI
    - uses: actions/upload-artifact@v3.1.3
      with:
        path: "./build"
  build_devtools_and_process_artifacts:
    if: ${{ !(${{ inputs.prerelease_commit_sha }}) }}
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:18.0-node
    needs:
    - download_build
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v3.0.2
      with:
        path: "."
    - uses: "./.github/actions/setup_node_modules"
    - run: "./scripts/circleci/pack_and_store_devtools_artifacts.sh"
      env:
        RELEASE_CHANNEL: experimental
    - uses: actions/upload-artifact@v3.1.3
      with:
        path: "./build/devtools.tgz"
  run_devtools_tests_for_versions:
    if: ${{ !(${{ inputs.prerelease_commit_sha }}) }}
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:18.0-node
    needs:
    - build_devtools_and_process_artifacts
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    strategy:
      matrix:
        version:
        - '16.0'
        - '16.5'
        - '16.8'
        - '17.0'
        - '18.0'
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v3.0.2
      with:
        path: "."
    - uses: "./.github/actions/setup_node_modules"
    - run: "./scripts/circleci/download_devtools_regression_build.js ${{ matrix.version }} --replaceBuild"
    - run: node ./scripts/jest/jest-cli.js --build --project devtools --release-channel=experimental --reactVersion ${{ matrix.version }} --ci
  run_devtools_e2e_tests_for_versions:
    if: ${{ !(${{ inputs.prerelease_commit_sha }}) }}
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:18.0-node
    needs:
    - build_devtools_and_process_artifacts
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    strategy:
      matrix:
        version:
        - '16.0'
        - '16.5'
        - '16.8'
        - '17.0'
        - '18.0'
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v3.0.2
      with:
        path: "."
    - uses: "./.github/actions/setup_node_modules"
    - name: Playwright install deps
      run: |-
        npx playwright install
        sudo npx playwright install-deps
    - run: "./scripts/circleci/download_devtools_regression_build.js ${{ matrix.version }}"
    - run: "./scripts/circleci/run_devtools_e2e_tests.js ${{ matrix.version }}"
      env:
        RELEASE_CHANNEL: experimental
    - name: Cleanup build regression folder
      run: rm -r ./build-regression
    - uses: actions/upload-artifact@v3.1.3
      with:
        path: "./tmp/screenshots"
