name: facebook/react/fuzz_tests
on:
  schedule:
  - cron: 0 * * * *
  workflow_dispatch:
    inputs:
      prerelease_commit_sha:
        required: false
jobs:
  test_fuzz:
    if: inputs.prerelease_commit_sha == ''
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'yarn'
    - uses: "./.github/actions/setup_node_modules"
    - name: Run fuzz tests
      run: |-
        FUZZ_TEST_SEED=$RANDOM yarn test fuzz --ci
        FUZZ_TEST_SEED=$RANDOM yarn test --prod fuzz --ci
